import { Schema } from 'mongoose';
import { baseFields, opts } from '../../../common';
import type {
  CrmFunnel,
  CrmOpportunity,
  CrmOpportunityActivity,
  CrmLead,
  CrmNote,
  CrmOpportunityNote,
  CrmTask,
  CrmPreferences,
} from './funnel';

export const CrmPreferencesSchemaMongo = new Schema<CrmPreferences>(
  {
    organizationId: { type: String, required: true, unique: true, index: true },
    createdBy: { type: String, required: true },
    updatedBy: { type: String, required: true },
    activityTypes: [
      {
        _id: false,
        id: { type: String, required: true },
        name: { type: String, required: true },
        color: { type: String, required: true },
        icon: { type: String, required: true },
      },
    ],
    salesTeams: [
      {
        _id: false,
        id: { type: String, required: true },
        name: { type: String, required: true },
        color: { type: String, required: true },
        icon: { type: String, required: true },
        leaderId: { type: String },
        members: [{ type: String }],
      },
    ],
  },
  { ...opts },
);

export const CrmFunnelSchemaMongo = new Schema<CrmFunnel>(
  {
    ...baseFields,
    organizationId: { type: String, required: true, index: true },
    createdBy: { type: String },
    updatedBy: { type: String },
    deletedBy: { type: String },
    name: { type: String, required: true },
    description: { type: String },
    isDefault: { type: Boolean, default: false },
    members: [{ type: String }],
    stages: [
      {
        _id: false,
        id: { type: String, required: true },
        name: { type: String, required: true },
        color: { type: String },
        order: { type: Number },
        probability: { type: Number, min: 0, max: 100 },
        description: { type: String },
        stagnationDays: { type: Number, min: 0 },
      },
    ],
  },
  { ...opts },
);
export const CrmOpportunitySchemaMongo = new Schema<CrmOpportunity>(
  {
    ...baseFields,
    organizationId: { type: String, required: true, index: true },
    createdBy: { type: String },
    updatedBy: { type: String },
    deletedBy: { type: String },
    funnelId: { type: String, required: true, index: true },
    stageId: { type: String, required: true, index: true },
    name: { type: String, required: true },
    contactId: { type: String },
    contactName: { type: String },
    companyId: { type: String },
    companyName: { type: String },
    value: { type: Number, min: 0 },
    currency: { type: String },
    expectedCloseDate: { type: Date },
    notes: { type: String },
    assignedToName: { type: String },
    tags: [{ type: String }],
    probability: { type: Number, min: 0, max: 100 },
    relatedDocumentType: { type: String },
    relatedDocumentId: { type: String },
    status: { type: String, enum: ['open', 'won', 'lost'], default: 'open' },
    order: { type: Number, default: 0 },
  },
  { ...opts },
);
export const CrmOpportunityActivitySchemaMongo = new Schema<CrmOpportunityActivity>(
  {
    ...baseFields,
    organizationId: { type: String, required: true, index: true },
    createdBy: { type: String, required: true },
    updatedBy: { type: String, required: true },
    deletedBy: { type: String },
    title: { type: String, required: true },
    type: { type: String, required: true },
    opportunityId: { type: String, index: true },
    opportunityName: { type: String },
    startsAt: { type: Date, required: true, index: true },
    endsAt: { type: Date, required: true },
    allDay: { type: Boolean, default: false },
    emailReminder: { type: Boolean, default: false },
    assignedTo: { type: String, index: true },
    assignedToName: { type: String },
    invitees: [{ type: String }],
    contactId: { type: String, index: true },
    notes: { type: String },
    completed: { type: Boolean, default: false },
  },
  { ...opts },
);
export const CrmLeadSchemaMongo = new Schema<CrmLead>(
  {
    ...baseFields,
    organizationId: { type: String, required: true, index: true },
    createdBy: { type: String },
    updatedBy: { type: String },
    deletedBy: { type: String },
    funnelId: { type: String, required: true, index: true },
    stageId: { type: String, required: true, index: true },
    name: { type: String, required: true },
    contactId: { type: String, required: true, index: true },
    contactName: { type: String, required: true },
    companyId: { type: String, index: true },
    companyName: { type: String },
    value: { type: Number, min: 0, default: 0 },
    currency: { type: String, default: 'COP' },
    expectedCloseDate: { type: Date },
    dueDate: { type: Date },
    potential: { type: Number, min: 0, max: 100 },
    notes: { type: String, default: '' },
    assignedToName: { type: String },
    assignedTo: { type: String, index: true },
    tags: [{ type: String }],
    probability: { type: Number, min: 0, max: 100 },
    relatedDocumentType: { type: String },
    relatedDocumentId: { type: String },
    status: { type: String, enum: ['open', 'won', 'lost'], default: 'open' },
    order: { type: Number, default: 0 },
    customFields: [
      {
        _id: false,
        fieldId: { type: String, required: true },
        value: { type: Schema.Types.Mixed },
      },
    ],
    stagnationDays: { type: Number, min: 0 },
  },
  { ...opts },
);
export const CrmNoteSchemaMongo = new Schema<CrmNote>(
  {
    ...baseFields,
    leadId: { type: String, required: true, index: true },
    content: { type: String, required: true },
    createdBy: { type: String, required: true },
    createdAt: { type: Date, required: true },
  },
  { ...opts },
);
export const CrmOpportunityNoteSchemaMongo = new Schema<CrmOpportunityNote>(
  {
    ...baseFields,
    organizationId: { type: String, required: true, index: true },
    opportunityId: { type: String, required: true, index: true },
    title: { type: String },
    content: { type: String, required: true },
    color: { type: String },
    createdBy: { type: String, required: true },
    createdAt: { type: Date, required: true },
  },
  { ...opts },
);
export const CrmTaskSchemaMongo = new Schema<CrmTask>(
  {
    ...baseFields,
    leadId: { type: String, required: true, index: true },
    title: { type: String, required: true },
    description: { type: String },
    dueDate: { type: Date },
    completed: { type: Boolean, default: false },
    assignedTo: { type: String },
    createdBy: { type: String, required: true },
    createdAt: { type: Date, required: true },
  },
  { ...opts },
);
