import { Schema } from 'mongoose';
import { baseFields, opts } from '../../../../common';
import type { Document } from './document';

export const DocumentSchemaMongo = new Schema<Document>(
  {
    ...baseFields,
    organizationId: { type: String, required: true, index: true },
    createdBy: { type: String },
    updatedBy: { type: String },
    deletedBy: { type: String },
    contactId: { type: String },
    contactName: { type: String },
    description: { type: String },
    date: { type: String },
    dueDate: { type: String },
    disbursementDate: { type: String },
    subtotal: { type: Number },
    discount: { type: Number },
    total: { type: Number },
    tax: { type: Number },
    currency: { type: String },
    status: { type: Number },
    tags: { type: [String] },
    lines: {
      type: [
        {
          _id: false,
          id: { type: String },
          concept: { type: String },
          description: { type: String },
          price: { type: Number },
          units: { type: Number },
          discount: { type: Number },
          tax: { type: Number },
          taxes: { type: [String] },
          tags: { type: [String] },
          productId: { type: String },
          variantId: { type: String },
          serviceId: { type: String },
          sku: { type: String },
          weight: { type: Number },
          costPrice: { type: Number },
          account: { type: String },
          projectId: { type: String },
          retention: { type: String },
          unitType: { type: String },
        },
      ],
      default: undefined,
    },
    paymentMethodId: { type: String },
    financialFeePaymentMethodId: { type: String },
    financialFeeName: { type: String },
    financialFeeType: { type: String },
    financialFeeValue: { type: Number },
    paymentsTotal: { type: Number },
    paymentsPending: { type: Number },
    language: { type: String },
    designId: { type: String },
    docType: { type: String, required: true, index: true },
    customFields: {
      type: [
        {
          _id: false,
          field: { type: String },
          value: { type: String },
        },
      ],
      default: undefined,
    },
    docNumber: { type: String },
  },
  { ...opts },
);
