export const DATA_SOURCES_KEY = 'dataSources';
export const MONGO_DATABASE_NAME = 'helebba';

export enum Collection {
  USERS = 'users',
  ORGANIZATIONS = 'organizations',
  PRODUCTS = 'products',
  CATEGORIES = 'categories',
  PRODUCT_FIELD_DEFINITIONS = 'product_field_definitions',
  CATALOGS = 'catalogs',
  POS_STORES = 'pos_stores',
  POS_RECEIPTS = 'pos_receipts',
  CRM_FUNNELS = 'crm_funnels',
  CRM_LEADS = 'crm_leads',
  CRM_OPPORTUNITIES = 'crm_opportunities',
  BRANDS = 'brands',
  CONTACTS = 'contacts',
  WAREHOUSES = 'warehouses',
  SESSIONS = 'sessions',
  API_KEYS = 'api_keys',
  MEMBERSHIPS = 'memberships',
  ROLES = 'roles',
  SUBSCRIPTIONS = 'subscriptions',
  SERVICES = 'services',
  DOCUMENTS = 'documents',
  PAYMENT_METHODS = 'payment_methods',
  PAYMENTS = 'payments',
  BANKING_ACCOUNTS = 'banking_accounts',
  TREASURY_MOVEMENTS = 'treasury_movements',
  PRODUCT_NOTES = 'product_notes',
  STOCK_MOVEMENTS = 'stock_movements',
  PRICE_LISTS = 'price_lists',
}
