export const PublicRoutes = {
  LOGIN: '/login',
  LOGIN_VERIFY: '/login/verify',
  SIGNUP: '/signup',
  SIGNUP_VERIFY: '/signup/verify',
  APPLE_CALLBACK: '/auth/oauth/apple/callback',
} as const;

export const PrivateRoutes = {
  ROOT: '/',
  ACCOUNTS: '/accounts',
  NEW_ACCOUNT: '/accounts/new',
  CONTACTS: '/contacts',
  CONTACT_DETAIL: '/contacts/:id',
  SERVICES: '/services',
  PRODUCTS: '/products',
  CATALOG: '/catalog',
  POS: '/pos',
  CRM_FUNNELS: '/crm/funnels',
  CRM_LEADS: '/crm/leads',
  CRM_LEAD_DETAIL: '/crm/leads/:leadId',
  CRM_LEAD_BOARD: '/crm/funnels/:funnelId/board',
  CATEGORIES: '/categories',
  BRANDS: '/brands',
  WAREHOUSES: '/inventory/warehouses',
  PAYMENTS: '/payments',
  BANK_ACCOUNTS: '/banking',
  DAHSBOARD: '/dahsboard',
  INVOICES: '/sales/revenue',
  ESTIMATES: '/sales/estimates',
  PURCHASES: '/purchases',
  PURCHASE_ORDERS: '/inventory/purchase-orders',
  SETUP: '/setup',
  TRIAL_EXPIRED: '/trial/expired',
} as const;
