import { PrivateRoutes } from '@/app/router/routes';
import type { NavigationItem } from './types';

export const defaultNavigation: NavigationItem[] = [
  {
    id: 'dashboard',
    name: 'Mi zona',
    path: '/employees/me',
    position: 1,
    isVisible: false,
    isSystem: true,
  },

  {
    id: 'contacts',
    name: 'Contactos',
    path: '/contacts',
    position: 2,
    isVisible: true,
    isSystem: true,
  },

  {
    id: 'sales',
    name: 'Ventas',
    path: '/sales/revenue',
    position: 3,
    isVisible: true,
    isSystem: true,
    children: [
      {
        id: 'sales.invoices',
        name: 'Facturas',
        path: PrivateRoutes.INVOICES,
        position: 1,
        isVisible: true,
        isSystem: true,
        parentId: 'sales',
      },
      {
        id: 'sales.quotes',
        name: 'Cotizaciones',
        path: '/sales/estimates',
        position: 2,
        isVisible: true,
        isSystem: true,
        parentId: 'sales',
      },
      {
        id: 'sales.services',
        name: 'Servicios',
        path: '/services',
        position: 3,
        isVisible: true,
        isSystem: true,
        parentId: 'sales',
      },
      {
        id: 'sales.crm',
        name: 'Embudo de ventas',
        path: '/crm/funnels',
        position: 5,
        isVisible: false,
        isSystem: true,
        parentId: 'sales',
      },
      {
        id: 'sales.pos',
        name: 'Punto de venta',
        path: '/pos',
        position: 6,
        isVisible: false,
        isSystem: true,
        parentId: 'sales',
      },
    ],
  },

  {
    id: 'expenses',
    name: 'Gastos',
    path: PrivateRoutes.PURCHASES,
    position: 4,
    isVisible: true,
    isSystem: true,
    children: [
      {
        id: 'expenses.documents',
        name: 'Facturas de compra',
        path: PrivateRoutes.PURCHASES,
        position: 1,
        isVisible: true,
        isSystem: true,
        parentId: 'expenses',
      },
      {
        id: 'expenses.recurring',
        name: 'Gastos recurrentes',
        path: '/expenses/recurring',
        position: 2,
        isVisible: false,
        isSystem: true,
        parentId: 'expenses',
      },
    ],
  },

  {
    id: 'inventory',
    name: 'Inventario',
    path: '/products',
    position: 5,
    isVisible: true,
    isSystem: true,
    children: [
      {
        id: 'inventory.control.panel',
        name: 'Panel de control',
        path: '/products',
        position: 1,
        isVisible: true,
        isSystem: true,
        parentId: 'inventory',
      },
      {
        id: 'inventory.products',
        name: 'Productos',
        path: '/products',
        position: 2,
        isVisible: true,
        isSystem: true,
        parentId: 'inventory',
      },
      {
        id: 'inventory.categories',
        name: 'Categorías',
        path: '/categories',
        position: 3,
        isVisible: true,
        isSystem: true,
        parentId: 'inventory',
      },
      {
        id: 'inventory.brands',
        name: 'Marcas',
        path: '/brands',
        position: 4,
        isVisible: true,
        isSystem: true,
        parentId: 'inventory',
      },
      {
        id: 'inventory.warehouses',
        name: 'Almacenes',
        path: '/inventory/warehouses',
        position: 5,
        isVisible: true,
        isSystem: true,
        parentId: 'inventory',
      },
      {
        id: 'inventory.movements',
        name: 'Movimientos',
        path: '/inventory/movements',
        position: 6,
        isVisible: false,
        isSystem: true,
        parentId: 'inventory',
      },
    ],
  },

  {
    id: 'purchases',
    name: 'Compras',
    path: '/purchases',
    position: 6,
    isVisible: false,
    isSystem: true,
    children: [
      {
        id: 'purchases.orders',
        name: 'Órdenes de compra',
        path: '/purchase-orders',
        position: 1,
        isVisible: true,
        isSystem: true,
        parentId: 'purchases',
      },
      {
        id: 'purchases.bills',
        name: 'Facturas proveedor',
        path: '/supplier-bills',
        position: 2,
        isVisible: true,
        isSystem: true,
        parentId: 'purchases',
      },
    ],
  },
  {
    id: 'banking',
    name: 'Finanzas',
    path: '/banking',
    position: 7,
    isVisible: true,
    isSystem: true,
    children: [
      {
        id: 'banking.accounts',
        name: 'Cuentas',
        path: PrivateRoutes.BANK_ACCOUNTS,
        position: 6,
        isVisible: true,
        isSystem: true,
        parentId: 'banking',
      },
      {
        id: 'banking.transactions',
        name: 'Movimientos',
        path: '/transactions',
        position: 2,
        isVisible: false,
        isSystem: true,
        parentId: 'banking',
      },
      {
        id: 'banking.transactions',
        name: 'Pagos y Cobros',
        path: '/payments',
        position: 1,
        isVisible: true,
        isSystem: true,
        parentId: 'banking',
      },
      {
        id: 'banking.reconciliation',
        name: 'Conciliación',
        path: '/reconciliation',
        position: 3,
        isVisible: false,
        isSystem: true,
        parentId: 'banking',
      },
    ],
  },
  {
    id: 'accounting',
    name: 'Contabilidad',
    path: '/accounting',
    position: 8,
    isVisible: false,
    isSystem: true,
    children: [
      {
        id: 'accounting.journal',
        name: 'Libro diario',
        path: '/journal',
        position: 1,
        isVisible: true,
        isSystem: true,
        parentId: 'accounting',
      },
      {
        id: 'accounting.chart',
        name: 'Plan de cuentas',
        path: '/chart-of-accounts',
        position: 2,
        isVisible: true,
        isSystem: true,
        parentId: 'accounting',
      },
      {
        id: 'accounting.reports',
        name: 'Reportes',
        path: '/accounting/reports',
        position: 3,
        isVisible: true,
        isSystem: true,
        parentId: 'accounting',
      },
    ],
  },
  {
    id: 'projects',
    name: 'Proyectos',
    path: '/projects',
    position: 9,
    isVisible: false,
    isSystem: true,
  },
  {
    id: 'hr',
    name: 'Equipo',
    path: '/team',
    position: 10,
    isVisible: false,
    isSystem: true,
    children: [
      {
        id: 'hr.members',
        name: 'Miembros',
        path: '/team/members',
        position: 1,
        isVisible: true,
        isSystem: true,
        parentId: 'hr',
      },
      {
        id: 'hr.roles',
        name: 'Roles',
        path: '/settings/roles',
        position: 2,
        isVisible: true,
        isSystem: true,
        parentId: 'hr',
      },
    ],
  },
  {
    id: 'analitics',
    name: 'Analitica',
    path: '/reporting',
    position: 11,
    isVisible: true,
    isSystem: true,
    children: [
      {
        id: 'analitics.reporting',
        name: 'Informes',
        path: '/reporting/sales',
        position: 1,
        isVisible: true,
        isSystem: true,
        parentId: 'analitics',
      },
    ],
  },
  {
    id: 'reports',
    name: 'Reportes',
    path: '/reports',
    position: 11,
    isVisible: false,
    isSystem: true,
  },
];
