#!/bin/sh

printf "Do you want to skip running tests on modified packages [y/N]: "
read -r should_skip < /dev/tty || should_skip="N"

if [ "$should_skip" != "y" ] && [ "$should_skip" != "Y" ]; then

  echo "Running tests..."

  STAGED=$(git diff --name-only --cached)
  package="/package.json"
  git="/.git"
  find_package() {
      parentDirectory=$(dirname "$1")
      if [ -f "$parentDirectory$package" ]; then
          RESULT="$parentDirectory$package"
      elif [ -d "$parentDirectory$git" ]; then
          RESULT=""
      else
          RESULT=$(find_package "$parentDirectory")
      fi
      printf '%s\n' "$RESULT"
  }
  list=""
  set -f
  IFS='
'
  for staged in $STAGED; do
      item=$(find_package "$staged")
      if [ -z "$item" ]; then
          echo "skipped $staged"
      elif grep -q precommit "$item"; then
          list="$list
$item"
      fi
  done
  files=$(printf '%s\n' "$list" | sed '/^$/d' | sort -u)
  set +f

  exitCode=0
  for file in $files; do
      fileDirectory=$(dirname "$file")
      echo
      echo "[$fileDirectory] > pnpm run -s precommit"
      cd "$fileDirectory" || exit 1

      pnpm run -s precommit || {
          echo
          echo "[$fileDirectory] > pre-commit hook failed (add --no-verify to bypass)"
          exitCode=1
      }
      cd - >/dev/null || exit 1
  done
  if [ "$exitCode" -eq 1 ]; then
    exit 1
  fi

fi
