import { Schema } from 'mongoose';
import { type Product } from './product';
import { baseFields, opts } from '../../../../common';

export const ProductSchemaMongo = new Schema<Product>(
  {
    ...baseFields,
    organizationId: { type: String, required: true, index: true },
    createdBy: { type: String },
    updatedBy: { type: String },
    deletedBy: { type: String },
    kind: { type: String },
    name: { type: String, required: true },
    slug: { type: String },
    brand: { type: String },
    description: { type: String },
    typeId: { type: String },
    inCatalog: { type: Boolean },
    inPos: { type: Boolean, default: false },
    images: { type: [String] },
    files: [
      {
        _id: false,
        id: { type: String },
        name: { type: String },
        url: { type: String },
        size: { type: Number },
        mimeType: { type: String },
      },
    ],
    minStock: { type: Number, min: 0, default: 0 },
    customFields: [
      {
        _id: false,
        definitionId: { type: String },
        field: { type: String },
        value: { type: Schema.Types.Mixed, required: true },
      },
    ],
    contactId: { type: String },
    contactName: { type: String },
    price: { type: Number, min: 0 },
    cost: { type: Number, min: 0 },
    stockState: { type: Number },
    taxes: { type: [String] },
    total: { type: Number, min: 0 },
    taxRate: { type: Number, min: 0 },
    hasStock: { type: Boolean },
    stock: { type: Number, min: 0 },
    barcode: { type: String },
    sku: { type: String },
    purchasePrice: { type: Number, min: 0 },
    weight: { type: Number, min: 0 },
    tags: { type: [String] },
    categoryId: { type: String, ref: 'categories' },
    categories: [{ type: String, ref: 'categories' }],
    categoryOptions: { type: String },
    factoryCode: { type: String },
    forSale: { type: Boolean },
    forPurchase: { type: Boolean },
    forProduction: { type: Boolean },
    forService: { type: Boolean },
    forRepair: { type: Boolean },
    forMaintenance: { type: Boolean },
    forRent: { type: Boolean },
    manageLots: { type: Boolean, default: false },
    manageSerials: { type: Boolean, default: false },
    salesAccountId: { type: String },
    purchaseAccountId: { type: String },
    salesChannelId: { type: String },
    expAccountId: { type: String },
    warehouseId: { type: String },
    companyId: { type: String },
    variants: {
      type: [
        {
          _id: false,
          id: { type: String },
          barcode: { type: String },
          name: { type: String },
          sku: { type: String },
          factoryCode: { type: String },
          price: { type: Number, min: 0 },
          // Mixed keeps legacy HEX strings readable while new writes persist { name, hex }.
          color: { type: Schema.Types.Mixed },
          size: { type: String },
          cost: { type: Number, min: 0 },
          weight: { type: Number, min: 0 },
          purchasePrice: { type: Number, min: 0 },
          stock: { type: Number, min: 0 },
          variantId: { type: String },
        },
      ],
      default: undefined,
    },
  },
  { ...opts },
);
