import { Schema } from 'mongoose';
import { type Product } from './product';
import { baseFields, opts } from '../../../../common';

export const ProductSchemaMongo = new Schema<Product>(
  {
    ...baseFields,
    organizationId: { type: String, required: true, index: true },
    createdBy: { type: String },
    updatedBy: { type: String },
    deletedBy: { type: String },
    kind: { type: String },
    name: { type: String, required: true },
    slug: { type: String },
    brand: { type: String },
    description: { type: String },
    typeId: { type: String },
    inCatalog: { type: Boolean },
    images: { type: [String] },
    customFields: [
      {
        field: { type: String, required: true },
        value: { type: String, required: true },
      },
    ],
    contactId: { type: String },
    contactName: { type: String },
    price: { type: Number },
    cost: { type: Number },
    stockState: { type: Number },
    taxes: { type: [String] },
    total: { type: Number },
    hasStock: { type: Boolean },
    stock: { type: Number },
    barcode: { type: String },
    sku: { type: String },
    purchasePrice: { type: Number },
    weight: { type: Number },
    tags: { type: [String] },
    categoryId: { type: String },
    categories: { type: [String] },
    categoryOptions: { type: String },
    factoryCode: { type: String },
    forSale: { type: Boolean },
    forPurchase: { type: Boolean },
    forProduction: { type: Boolean },
    forService: { type: Boolean },
    forRepair: { type: Boolean },
    forMaintenance: { type: Boolean },
    forRent: { type: Boolean },
    salesChannelId: { type: String },
    expAccountId: { type: String },
    warehouseId: { type: String },
    companyId: { type: String },
    variants: {
      type: [
        {
          _id: false,
          id: { type: String },
          barcode: { type: String },
          name: { type: String },
          sku: { type: String },
          factoryCode: { type: String },
          price: { type: Number },
          color: { type: String },
          size: { type: String },
          cost: { type: Number },
          weight: { type: Number },
          purchasePrice: { type: Number },
          stock: { type: Number },
          variantId: { type: String },
        },
      ],
      default: undefined,
    },
  },
  { ...opts },
);
